/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const ReferralRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'refereeId' : IDL.Principal,
  'referredAt' : IDL.Int,
  'referrerId' : IDL.Principal,
  'referredAmount' : IDL.Nat,
  'commissionAmount' : IDL.Nat,
  'commissionRate' : IDL.Float64,
  'purchaseId' : IDL.Nat,
  'courseId' : IDL.Text,
});
export const ReferralCode = IDL.Record({
  'code' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Int,
  'usageCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'discount' : IDL.Nat,
  'commissionRate' : IDL.Float64,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const WithdrawalRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
  'userId' : IDL.Principal,
  'processedAt' : IDL.Opt(IDL.Int),
  'upiId' : IDL.Text,
  'amount' : IDL.Nat,
  'requestedAt' : IDL.Int,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activateReferralCodeById' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelReferralRecord' : IDL.Func([IDL.Nat], [], []),
  'cancelWithdrawal' : IDL.Func([IDL.Nat], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createReferralCode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
  'createReferralRecord' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'deactivateReferralCode' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPaidReferralList' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
  'getPendingReferralList' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
  'getReferralCode' : IDL.Func([IDL.Text], [IDL.Opt(ReferralCode)], ['query']),
  'getReferralCodeById' : IDL.Func([IDL.Nat], [ReferralCode], ['query']),
  'getReferralCodes' : IDL.Func([], [IDL.Vec(ReferralCode)], ['query']),
  'getReferralCountByUser' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
  'getReferralRecord' : IDL.Func([IDL.Nat], [ReferralRecord], []),
  'getReferralRecordList' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
  'getReferralRecordsByReferrer' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReferralRecord)],
      ['query'],
    ),
  'getReferralRecordsByUserId' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ReferralRecord)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTotalReferralCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalReferralRevenue' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserWithdrawals' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'getWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
  'getWithdrawalsByStatus' : IDL.Func(
      [IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
      [IDL.Vec(WithdrawalRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isReferralCodeActive' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isValidReferralCode' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'requestWithdrawal' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'setReferralStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
      [],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateReferralDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateReferralRecord' : IDL.Func([IDL.Nat, ReferralRecord], [], []),
  'updateWithdrawalStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
      [],
      [],
    ),
  'validateReferralCodeById' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const ReferralRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'refereeId' : IDL.Principal,
    'referredAt' : IDL.Int,
    'referrerId' : IDL.Principal,
    'referredAmount' : IDL.Nat,
    'commissionAmount' : IDL.Nat,
    'commissionRate' : IDL.Float64,
    'purchaseId' : IDL.Nat,
    'courseId' : IDL.Text,
  });
  const ReferralCode = IDL.Record({
    'code' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Int,
    'usageCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'discount' : IDL.Nat,
    'commissionRate' : IDL.Float64,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const WithdrawalRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null }),
    'userId' : IDL.Principal,
    'processedAt' : IDL.Opt(IDL.Int),
    'upiId' : IDL.Text,
    'amount' : IDL.Nat,
    'requestedAt' : IDL.Int,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activateReferralCodeById' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelReferralRecord' : IDL.Func([IDL.Nat], [], []),
    'cancelWithdrawal' : IDL.Func([IDL.Nat], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createReferralCode' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Nat], []),
    'createReferralRecord' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'deactivateReferralCode' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPaidReferralList' : IDL.Func([], [IDL.Vec(ReferralRecord)], ['query']),
    'getPendingReferralList' : IDL.Func(
        [],
        [IDL.Vec(ReferralRecord)],
        ['query'],
      ),
    'getReferralCode' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ReferralCode)],
        ['query'],
      ),
    'getReferralCodeById' : IDL.Func([IDL.Nat], [ReferralCode], ['query']),
    'getReferralCodes' : IDL.Func([], [IDL.Vec(ReferralCode)], ['query']),
    'getReferralCountByUser' : IDL.Func([IDL.Principal], [IDL.Nat], ['query']),
    'getReferralRecord' : IDL.Func([IDL.Nat], [ReferralRecord], []),
    'getReferralRecordList' : IDL.Func(
        [],
        [IDL.Vec(ReferralRecord)],
        ['query'],
      ),
    'getReferralRecordsByReferrer' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReferralRecord)],
        ['query'],
      ),
    'getReferralRecordsByUserId' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ReferralRecord)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTotalReferralCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalReferralRevenue' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserWithdrawals' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'getWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalRequest)], ['query']),
    'getWithdrawalsByStatus' : IDL.Func(
        [IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
        [IDL.Vec(WithdrawalRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isReferralCodeActive' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isValidReferralCode' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'requestWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'setReferralStatus' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
        [],
        [],
      ),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateReferralDiscount' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateReferralRecord' : IDL.Func([IDL.Nat, ReferralRecord], [], []),
    'updateWithdrawalStatus' : IDL.Func(
        [IDL.Nat, IDL.Variant({ 'pending' : IDL.Null, 'paid' : IDL.Null })],
        [],
        [],
      ),
    'validateReferralCodeById' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };