/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ReferralCode {
  'code' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'usageCount' : bigint,
  'isActive' : boolean,
  'discount' : bigint,
  'commissionRate' : number,
}
export interface ReferralRecord {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'paid' : null },
  'refereeId' : Principal,
  'referredAt' : bigint,
  'referrerId' : Principal,
  'referredAmount' : bigint,
  'commissionAmount' : bigint,
  'commissionRate' : number,
  'purchaseId' : bigint,
  'courseId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WithdrawalRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'paid' : null },
  'userId' : Principal,
  'processedAt' : [] | [bigint],
  'upiId' : string,
  'amount' : bigint,
  'requestedAt' : bigint,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'activateReferralCodeById' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelReferralRecord' : ActorMethod<[bigint], undefined>,
  'cancelWithdrawal' : ActorMethod<[bigint], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createReferralCode' : ActorMethod<[string, bigint], bigint>,
  'createReferralRecord' : ActorMethod<[bigint, string, bigint], bigint>,
  'deactivateReferralCode' : ActorMethod<[bigint], undefined>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPaidReferralList' : ActorMethod<[], Array<ReferralRecord>>,
  'getPendingReferralList' : ActorMethod<[], Array<ReferralRecord>>,
  'getReferralCode' : ActorMethod<[string], [] | [ReferralCode]>,
  'getReferralCodeById' : ActorMethod<[bigint], ReferralCode>,
  'getReferralCodes' : ActorMethod<[], Array<ReferralCode>>,
  'getReferralCountByUser' : ActorMethod<[Principal], bigint>,
  'getReferralRecord' : ActorMethod<[bigint], ReferralRecord>,
  'getReferralRecordList' : ActorMethod<[], Array<ReferralRecord>>,
  'getReferralRecordsByReferrer' : ActorMethod<
    [Principal],
    Array<ReferralRecord>
  >,
  'getReferralRecordsByUserId' : ActorMethod<
    [Principal],
    Array<ReferralRecord>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTotalReferralCount' : ActorMethod<[], bigint>,
  'getTotalReferralRevenue' : ActorMethod<[], bigint>,
  'getUserWithdrawals' : ActorMethod<[Principal], Array<WithdrawalRequest>>,
  'getWithdrawals' : ActorMethod<[], Array<WithdrawalRequest>>,
  'getWithdrawalsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'paid' : null }],
    Array<WithdrawalRequest>
  >,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isReferralCodeActive' : ActorMethod<[bigint], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isValidReferralCode' : ActorMethod<[bigint], boolean>,
  'requestWithdrawal' : ActorMethod<[string, Principal, bigint], bigint>,
  'setReferralStatus' : ActorMethod<
    [bigint, { 'pending' : null } | { 'paid' : null }],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateReferralDiscount' : ActorMethod<[bigint, bigint], undefined>,
  'updateReferralRecord' : ActorMethod<[bigint, ReferralRecord], undefined>,
  'updateWithdrawalStatus' : ActorMethod<
    [bigint, { 'pending' : null } | { 'paid' : null }],
    undefined
  >,
  'validateReferralCodeById' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];