/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface ReferralRecord {
    id: bigint;
    status: Variant_pending_paid;
    refereeId: Principal;
    referredAt: bigint;
    referrerId: Principal;
    referredAmount: bigint;
    commissionAmount: bigint;
    commissionRate: number;
    purchaseId: bigint;
    courseId: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface WithdrawalRequest {
    id: bigint;
    status: Variant_pending_paid;
    userId: Principal;
    processedAt?: bigint;
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface ReferralCode {
    code: string;
    userId: Principal;
    createdAt: bigint;
    usageCount: bigint;
    isActive: boolean;
    discount: bigint;
    commissionRate: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_pending_paid {
    pending = "pending",
    paid = "paid"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activateReferralCodeById(id: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelReferralRecord(id: bigint): Promise<void>;
    cancelWithdrawal(withdrawalId: bigint): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createReferralCode(code: string, discount: bigint): Promise<bigint>;
    createReferralRecord(referralCodeId: bigint, courseId: string, referredAmount: bigint): Promise<bigint>;
    deactivateReferralCode(id: bigint): Promise<void>;
    getCallerUserRole(): Promise<UserRole>;
    getPaidReferralList(): Promise<Array<ReferralRecord>>;
    getPendingReferralList(): Promise<Array<ReferralRecord>>;
    getReferralCode(code: string): Promise<ReferralCode | null>;
    getReferralCodeById(id: bigint): Promise<ReferralCode>;
    getReferralCodes(): Promise<Array<ReferralCode>>;
    getReferralCountByUser(referrerId: Principal): Promise<bigint>;
    getReferralRecord(id: bigint): Promise<ReferralRecord>;
    getReferralRecordList(): Promise<Array<ReferralRecord>>;
    getReferralRecordsByReferrer(referrerId: Principal): Promise<Array<ReferralRecord>>;
    getReferralRecordsByUserId(userId: Principal): Promise<Array<ReferralRecord>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTotalReferralCount(): Promise<bigint>;
    getTotalReferralRevenue(): Promise<bigint>;
    getUserWithdrawals(userId: Principal): Promise<Array<WithdrawalRequest>>;
    getWithdrawals(): Promise<Array<WithdrawalRequest>>;
    getWithdrawalsByStatus(status: Variant_pending_paid): Promise<Array<WithdrawalRequest>>;
    isCallerAdmin(): Promise<boolean>;
    isReferralCodeActive(id: bigint): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    isValidReferralCode(id: bigint): Promise<boolean>;
    requestWithdrawal(upiId: string, userId: Principal, amount: bigint): Promise<bigint>;
    setReferralStatus(id: bigint, status: Variant_pending_paid): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateReferralDiscount(id: bigint, discount: bigint): Promise<void>;
    updateReferralRecord(id: bigint, record: ReferralRecord): Promise<void>;
    updateWithdrawalStatus(withdrawalId: bigint, status: Variant_pending_paid): Promise<void>;
    validateReferralCodeById(code: bigint): Promise<void>;
}
import type { ReferralCode as _ReferralCode, ReferralRecord as _ReferralRecord, StripeSessionStatus as _StripeSessionStatus, UserRole as _UserRole, WithdrawalRequest as _WithdrawalRequest } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activateReferralCodeById(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateReferralCodeById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateReferralCodeById(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelReferralRecord(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelReferralRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelReferralRecord(arg0);
            return result;
        }
    }
    async cancelWithdrawal(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelWithdrawal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelWithdrawal(arg0);
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createReferralCode(arg0: string, arg1: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferralCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferralCode(arg0, arg1);
            return result;
        }
    }
    async createReferralRecord(arg0: bigint, arg1: string, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createReferralRecord(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReferralRecord(arg0, arg1, arg2);
            return result;
        }
    }
    async deactivateReferralCode(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateReferralCode(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaidReferralList(): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaidReferralList();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaidReferralList();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingReferralList(): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingReferralList();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingReferralList();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralCode(arg0: string): Promise<ReferralCode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCode(arg0);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCode(arg0);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralCodeById(arg0: bigint): Promise<ReferralCode> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCodeById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCodeById(arg0);
            return result;
        }
    }
    async getReferralCodes(): Promise<Array<ReferralCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCodes();
            return result;
        }
    }
    async getReferralCountByUser(arg0: Principal): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralCountByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralCountByUser(arg0);
            return result;
        }
    }
    async getReferralRecord(arg0: bigint): Promise<ReferralRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralRecord(arg0);
                return from_candid_ReferralRecord_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralRecord(arg0);
            return from_candid_ReferralRecord_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralRecordList(): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralRecordList();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralRecordList();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralRecordsByReferrer(arg0: Principal): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralRecordsByReferrer(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralRecordsByReferrer(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReferralRecordsByUserId(arg0: Principal): Promise<Array<ReferralRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReferralRecordsByUserId(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReferralRecordsByUserId(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalReferralCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalReferralCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalReferralCount();
            return result;
        }
    }
    async getTotalReferralRevenue(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalReferralRevenue();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalReferralRevenue();
            return result;
        }
    }
    async getUserWithdrawals(arg0: Principal): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWithdrawals(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWithdrawals(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawals(): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawals();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawals();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWithdrawalsByStatus(arg0: Variant_pending_paid): Promise<Array<WithdrawalRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWithdrawalsByStatus(to_candid_variant_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWithdrawalsByStatus(to_candid_variant_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isReferralCodeActive(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isReferralCodeActive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isReferralCodeActive(arg0);
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async isValidReferralCode(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isValidReferralCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isValidReferralCode(arg0);
            return result;
        }
    }
    async requestWithdrawal(arg0: string, arg1: Principal, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0, arg1, arg2);
            return result;
        }
    }
    async setReferralStatus(arg0: bigint, arg1: Variant_pending_paid): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setReferralStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setReferralStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateReferralDiscount(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferralDiscount(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferralDiscount(arg0, arg1);
            return result;
        }
    }
    async updateReferralRecord(arg0: bigint, arg1: ReferralRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReferralRecord(arg0, to_candid_ReferralRecord_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReferralRecord(arg0, to_candid_ReferralRecord_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateWithdrawalStatus(arg0: bigint, arg1: Variant_pending_paid): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWithdrawalStatus(arg0, to_candid_variant_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async validateReferralCodeById(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.validateReferralCodeById(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateReferralCodeById(arg0);
            return result;
        }
    }
}
function from_candid_ReferralRecord_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReferralRecord): ReferralRecord {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalRequest): WithdrawalRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReferralCode]): ReferralCode | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        paid: null;
    };
    userId: Principal;
    processedAt: [] | [bigint];
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
}): {
    id: bigint;
    status: Variant_pending_paid;
    userId: Principal;
    processedAt?: bigint;
    upiId: string;
    amount: bigint;
    requestedAt: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n8(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        processedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.processedAt)),
        upiId: value.upiId,
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        pending: null;
    } | {
        paid: null;
    };
    refereeId: Principal;
    referredAt: bigint;
    referrerId: Principal;
    referredAmount: bigint;
    commissionAmount: bigint;
    commissionRate: number;
    purchaseId: bigint;
    courseId: string;
}): {
    id: bigint;
    status: Variant_pending_paid;
    refereeId: Principal;
    referredAt: bigint;
    referrerId: Principal;
    referredAmount: bigint;
    commissionAmount: bigint;
    commissionRate: number;
    purchaseId: bigint;
    courseId: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n8(_uploadFile, _downloadFile, value.status),
        refereeId: value.refereeId,
        referredAt: value.referredAt,
        referrerId: value.referrerId,
        referredAmount: value.referredAmount,
        commissionAmount: value.commissionAmount,
        commissionRate: value.commissionRate,
        purchaseId: value.purchaseId,
        courseId: value.courseId
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n12(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
}): Variant_pending_paid {
    return "pending" in value ? Variant_pending_paid.pending : "paid" in value ? Variant_pending_paid.paid : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalRequest>): Array<WithdrawalRequest> {
    return value.map((x)=>from_candid_WithdrawalRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ReferralRecord>): Array<ReferralRecord> {
    return value.map((x)=>from_candid_ReferralRecord_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ReferralRecord_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReferralRecord): _ReferralRecord {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_pending_paid;
    refereeId: Principal;
    referredAt: bigint;
    referrerId: Principal;
    referredAmount: bigint;
    commissionAmount: bigint;
    commissionRate: number;
    purchaseId: bigint;
    courseId: string;
}): {
    id: bigint;
    status: {
        pending: null;
    } | {
        paid: null;
    };
    refereeId: Principal;
    referredAt: bigint;
    referrerId: Principal;
    referredAmount: bigint;
    commissionAmount: bigint;
    commissionRate: number;
    purchaseId: bigint;
    courseId: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n18(_uploadFile, _downloadFile, value.status),
        refereeId: value.refereeId,
        referredAt: value.referredAt,
        referrerId: value.referrerId,
        referredAmount: value.referredAmount,
        commissionAmount: value.commissionAmount,
        commissionRate: value.commissionRate,
        purchaseId: value.purchaseId,
        courseId: value.courseId
    };
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_paid): {
    pending: null;
} | {
    paid: null;
} {
    return value == Variant_pending_paid.pending ? {
        pending: null
    } : value == Variant_pending_paid.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
